version: 2

builds:
  - id: wardgate
    main: ./cmd/wardgate
    binary: wardgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: wardgate-cli
    main: ./cmd/wardgate-cli
    binary: wardgate-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.configPath=/etc/wardgate-cli/config.yaml

archives:
  - id: wardgate
    ids:
      - wardgate
    formats: [tar.gz]
    name_template: "wardgate_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - config.yaml.example
      - presets/*

  - id: wardgate-cli
    ids:
      - wardgate-cli
    formats: [tar.gz]
    name_template: "wardgate-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - config.yaml.example
      - presets/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dockers_v2:
  - ids:
      - wardgate
    images:
      - "avoutic/wardgate"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - presets
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

release:
  github:
    owner: wardgate
    name: wardgate
  draft: false
  prerelease: auto
