version: 2

builds:
  - id: wardgate
    main: ./cmd/wardgate
    binary: wardgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: wardgate-cli
    main: ./cmd/wardgate-cli
    binary: wardgate-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.configPath=/etc/wardgate-cli/config.yaml

  - id: wardgate-exec
    main: ./cmd/wardgate-exec
    binary: wardgate-exec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: wardgate
    ids:
      - wardgate
    formats: [tar.gz]
    name_template: "wardgate_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - config.yaml.example
      - presets/*

  - id: wardgate-cli
    ids:
      - wardgate-cli
    formats: [tar.gz]
    name_template: "wardgate-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

  - id: wardgate-exec
    ids:
      - wardgate-exec
    formats: [tar.gz]
    name_template: "wardgate-exec_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dockers_v2:
  - ids:
      - wardgate
    images:
      - "avoutic/wardgate"
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - presets
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"

brews:
  - ids: [wardgate]
    repository:
      owner: wardgate
      name: homebrew-wardgate
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wardgate/wardgate"
    description: "API gateway for AI agents - server"
    license: "AGPL-3.0"
    install: |
      bin.install "wardgate"

  - ids: [wardgate-cli]
    repository:
      owner: wardgate
      name: homebrew-wardgate
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wardgate/wardgate"
    description: "API gateway for AI agents - CLI client"
    license: "AGPL-3.0"
    install: |
      bin.install "wardgate-cli"

  - ids: [wardgate-exec]
    repository:
      owner: wardgate
      name: homebrew-wardgate
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/wardgate/wardgate"
    description: "API gateway for AI agents - conclave executor"
    license: "AGPL-3.0"
    install: |
      bin.install "wardgate-exec"

release:
  github:
    owner: wardgate
    name: wardgate
  draft: false
  prerelease: auto
